{"ts":1362335378037,"silentsave":true,"restoring":false,"patch":[[]],"length":0}
{"contributors":[],"silentsave":false,"ts":1362335388630,"patch":[[{"diffs":[[1,"all: js/d3\n\njs/d3:\n    cd js && git clone git://github.com/mbostock/d3.git && cd d3 && npm install && npm test\n"]],"start1":0,"start2":0,"length1":0,"length2":111}]],"length":111,"saved":false}
{"ts":1362335460426,"patch":[[{"diffs":[[0,"/d3\n"],[1,"js:\n    mkdir js"],[0,"\njs/d3:"],[1," js"],[0,"\n   "]],"start1":7,"start2":7,"length1":15,"length2":34}]],"length":130,"saved":false}
{"ts":1362335462938,"patch":[[{"diffs":[[0,": js/d3\n"],[1,"\n"],[0,"js:\n    "]],"start1":3,"start2":3,"length1":16,"length2":17}]],"length":131,"saved":false}
{"ts":1362335502808,"patch":[[{"diffs":[[0,"d3\n\njs:\n"],[-1,"    "],[1,"\t"],[0,"mkdir js"]],"start1":8,"start2":8,"length1":20,"length2":17},{"diffs":[[0," js\n"],[-1,"    "],[1,"\t"],[0,"cd j"]],"start1":32,"start2":32,"length1":12,"length2":9}]],"length":125,"saved":false}
